{
 "title": "SLI Overview",
 "description": "Just a non functional PoC (Not everything is working, just show casing something)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "feature",
    "query": {
     "query": "label_values(slo:sli:ratio_rate5m,feature)"
    }
   },
   { "name": "slo", "label": "SLO", "query": "0.9,0.95,0.98,0.99" },
   { "name": "window", "label": "Window", "query": "5m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Count of SLIs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(slo:sli:ratio_rate$window{feature=~\"$feature\"})"
    }
   ]
  },
  {
   "title": "Count of Features",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(feature) (slo:sli:ratio_rate$window{feature=~\"$feature\"}))"
    }
   ]
  },
  {
   "title": "Consumed Budgets Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(1 - (1 - slo:sli:ratio_rate$window{feature=~\"$feature\"}) / (1 - $slo) < 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Remaining Error Budgets ($window window)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (1 - slo:sli:ratio_rate$window{feature=~\"$feature\"}) / (1 - $slo)"
    }
   ]
  }
 ]
}