apiVersion: v1
kind: Namespace
metadata:
  name: blog-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: blog-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: blog_db
            - name: POSTGRES_USER
              value: blog
            - name: POSTGRES_PASSWORD
              value: islamghany
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: blog-system
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: ClusterIP
