apiVersion: v1
kind: Namespace
metadata:
  name: blog-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog-system

spec:
  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      labels:
        app: blog

    spec:
      initContainers:
        - name: init-migrate-seed
          image: localhost/islamghany/blog-api:0.0.1
          imagePullPolicy: Never
          command: ["./admin", "migrate,seed"]
          envFrom:
            - configMapRef:
                name: blog-config

      containers:
        - name: blog
          image: localhost/islamghany/blog-api:0.0.1
          imagePullPolicy: Never

          # k8s uses livenessProbe to know when to restart a container
          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          # k8s uses readinessProbe to wait for a container to be ready to start receiving traffic
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          ports:
            - name: blog
              containerPort: 8000
            - name: blog-debug
              containerPort: 8001
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          envFrom:
            - configMapRef:
                name: blog-config
