apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-system
spec:
  selector:
    app: blog
  ports:
    - name: blog
      port: 8000
      targetPort: sales
    - name: blog-debug
      port: 8001
      targetPort: blog-debug

  type: LoadBalancer
