apiVersion: v1
kind: Secret
metadata:
  name: blog-secret
  namespace: blog-system

type: Opaque
data:
  DB_USER: YmxvZw==
  DB_PASSWORD: aXNsYW1naGFueQ==
  JWT_SECRET: YmQ0ZTQxMDllNDBlZTk4Zjg0YjAxN2Q1ZmQ0MjFhNTlmODcyYjlkOGIyZGZlZjk4NjQ1ZTQ3Y2Y4MzQ2MjhhNQ==
